# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Liam Blake
description:      Applied mathematician & postgraduate student
url:              http://liamblake.github.io
baseurl:          /

paginate:         5

# Includes & excludes
include: ['_pages']
exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - vendor
keep_files:
  - CNAME
  - .nojekyll
  - .git

# Plugins 
plugins:
  - jekyll-paginate

