baseURL = 'http://liamblake.github.io/'
languageCode = 'en-us'
title = 'Liam Blake'
theme = 'apero'

[params]
  textFontFamily = "Commissioner"
  headingFontFamily = "Metropolis"

	socialInHeader = true
  socialInFooter = false
	[[params.social]]
		icon = "linkedin"
		icon_pack = "fab"
		url = "https://www.linkedin.com/in/liam-blake/"
	[[params.social]]
		icon = "orcid"
		icon_pack = "fab"
		url = "https://orcid.org/0000-0003-2779-494X"
	[[params.social]]
		icon = "github"
		icon_pack = "fab"
		url = "https://github.com/liamblake"

[menu]
	[[menu.header]]
		name = "Home"
		title = "Home"
		url = "/"
		weight = 1
	[[menu.header]]
		name = "Research"
		title = "Research & Publications"
		url = "/research"
		weight = 2
	[[menu.header]]
    name = "Talks"
    title = "Talks"
    url = "/talks/"
    weight = 3
